default-language: ru

database:
  # в большинстве случаев менять не надо, глобальные настройки для модуля DatabaseAPI (и всех плагинов, использующих его)
  data:
    # в теории можно добавить новые SQL типы, но я не пробовал
    sqlite:
      type: file
      driver:
        domain: "sqlite"
        class: "org.sqlite.JDBC"
    mysql:
      type: remote
      driver:
        domain: "mysql"
        class: "com.mysql.jdbc.Driver"

  # настройки подключения для AncapPlugin
  connection:
    # только те, что прописаны в data
    type: sqlite
    remote:
      host: "127.0.0.1"
      name: "ancap-plugin-database"
      user: "ancap-plugin-user"
      password: "qwerty"
      port: 3306
    file:
      name: "langs.db"