# не менять, отвечает за обновление конфига и автоперенос значений
configuration-version: 1

default-language: ru

database:
  
  main-database:
    
    # доступные по умолчанию - sqlite, mysql. Подробнее о типах смотрите на вики github.com/ancap-dev/AncapFramework/wiki
    type: sqlite
    remote:
      host: "127.0.0.1"
      name: "ancap-plugin-database"
      user: "ancap-plugin-user"
      password: "qwerty"
      port: 3306
    file:
      # будет создана в папке плагина
      name: "languages.db"

  scheduler-database:
    # обязательно должна быть локальная БД
    type: sqlite
    file:
      # будет создана в папке плагина
      name: "scheduler.db"