default-language: ru

# Will work in 1.7.
language:
  # Full localization. Fallback module's last hope.
  server-native: ru
  
  # If a localized resource isn't found, fallback module can try to find it in another language.
  # Fallback priority is follows: requested, target, default, native.
  # Lists ([code1, code2]) are supported as well as singular strings. Order matters.
  fallback:
    # english is known worldwide
    default: en
    target:
      # languages of post-soviet countries
      uk: ru
      kk: ru
      be: ru

      # portuguese and spanish are similar
      pt: es
      es: pt
      
      # don't change — used for auto-testing
      test_lang: [test_lang2, test_lang3]

database:
  
  main-database:
    
    # доступные по умолчанию - sqlite, mysql. Подробнее о типах смотрите на вики github.com/ancap-dev/AncapFramework/wiki
    type: sqlite
    remote:
      host: "127.0.0.1"
      name: "ancap-plugin-database"
      user: "ancap-plugin-user"
      password: "qwerty"
      port: 3306
    file:
      # будет создана в папке плагина
      name: "languages.db"

  scheduler-database:
    # обязательно должна быть локальная БД
    type: sqlite
    file:
      # будет создана в папке плагина
      name: "scheduler.db"

# DONT CHANGE SECTION

# Responsible for automatic updates and value transfers
configuration-version: 4

# Used to check if configuration works correctly 
test:
  string: "foo"
  integer: 420
  section:
    boolean: true